### ISSUE TITLE
[ICONS] Add all iland icons to fontastic account

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#1]
We need to have the whole list of iland cloud icons in SVG format with all declinaison (solid or/and not, with/without badges. If multiple badges possible, we need each version of the icon with different bages), uploaded to our [Fontastic](http://app.fontastic.me/#select/gQ29bDwukM24TuzwoMMxEK) account in separated sets : 
- iland cloud core (for core icons)
- iland cloud chart (for chart icons)
- And so on (if needed).

Constraints : 
- Each SVG icons should have a `viewBox` of `0 0 36 36`
- Each SVG icon should be well cut and centered so that we always have a square of 36x36px in size for each of them.

Example of SVG icon :
`<svg version="1.1" width="36" height="36"  viewBox="0 0 36 36" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>user-line</title>
    <path d="M18,17a7,7,0,1,0-7-7A7,7,0,0,0,18,17ZM18,5a5,5,0,1,1-5,5A5,5,0,0,1,18,5Z" class="clr-i-outline clr-i-outline-path-1"></path>
    <path d="M30.47,24.37a17.16,17.16,0,0,0-24.93,0A2,2,0,0,0,5,25.74V31a2,2,0,0,0,2,2H29a2,2,0,0,0,2-2V25.74A2,2,0,0,0,30.47,24.37ZM29,31H7V25.73a15.17,15.17,0,0,1,22,0h0Z" class="clr-i-outline clr-i-outline-path-2"></path>
    <rect x="0" y="0" width="36" height="36" fill-opacity="0"/>
</svg>`

**Comment by mathieupkf** [comment]
@JoMas971 - Updated on Fontastic

**Comment by JoMas971** [comment]
All icons have been implemented now. So i close this issue.
