### ISSUE TITLE
[UI] Look and Feel for input datetime component

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#10]
It would be great to have a complete design use case to cover this component.

This is the current screen for this component : https://projects.invisionapp.com/d/main#/console/6412142/226730682/preview

We would need to have more explicit design, like cases with or without error messages (including respective icons) and the check icon in case of valid input value.

It's also important to know that this component is dynamic and that we could decide to only display parts of it (like only the date or only the time etc...).
There are all cases that we need to cover design speaking : 

|`date`|
|`hours` [+ `minute` [+ `seconds`]]|. (time only: everything within `[]` mean optional)
|`date` + `hours`|
|`date` + `hours` + `minutes`|
|`date` + `hours` + `minutes` + `seconds`|

Also, we need to know what is the `min` and `max` __width__ for the calendar. The field itself could take 100% of available width. But the calendar is a bit different, it will be weird to make the calendar take all the with... We need to keep it dynamic but with boundaries :-).

**Comment by mathieupkf** [comment]
@JoMas971 - I grouped all elements inside a new screen called "components". It's on Secure Cloud V9 project on InVision (not anymore on V8). You'll find all components you need for date pickers. Let me know if you need anything else. 
https://projects.invisionapp.com/d/main#/console/12026582/345528567/preview

**Comment by JoMas971** [comment]
@mathieupkf thanks ! That looks great, but can i have the min/max width for the calendar please ? 
Also, i don't understand what is the purpose of double arrows in calendar header, can you tel me what it is ? 
Also, you didn't handle the case where the field has an error state. I don't know where to put the error icon (neither the others : help, valid) in your design :-/

**Comment by mathieupkf** [comment]
@JoMas971 
- I designed a new field for displaying error icons. I think we should display only one icon when we have an error. I mean that we should remove Arrow/Calendar/... icons to display the error one.
- Doubles arrows allow user to move year by year (it will replace our complex year switcher)
- For the calendar, the width is not related to field widths anymore. I think it will be easier for you. So I suggest to use a static width (300px). What do you think?

**Comment by JoMas971** [comment]
@mathieupkf 

- i'm not sure about the double arrows to change the year. It doesn't looks natural... 
Also, we will use [Clarity system](https://clarity.design/documentation/datepicker) for calendar, so the month and year are clickable and you can choose the value you want from the different views. You also have a "today" icon to set the date to current day. You can play with their calendar to see what i'm talking about.
Having the double arrow to switch the year is a good solution only to select next or previous year, but it's not a good solution if you want to go 3+ years backward or forward... 
Lets say we want to choose a date that is 10 years ago, we would click 10 times on the back double arrow vs 3 times with our current solution.
Another exemple : lets say we want a filter that show all invoices that are 5 or 10 years old, with the Clarity solution it's pretty simple, its only 3 clicks, but with the double arrow solution it's 5 to 10 clicks. And i don't take the month into account there...
Lets say we are the 10th of June and that we want to create an alert for the 1st of December, we will click 6 times to go from June to December... That is not a good option.
(what do you think @cfsnyder ?)

- About the error icons, it doesn't feel natural to me to replace the arrow icon of a dropdown... But i don't have a better solution to share, so i'll go for this unless somebody have a better one.

- Ok for calendar size. And i suppose that the position of the calendar in your design is what you want right ? I'm used to more aligned element from you :-P.

**Comment by mathieupkf** [comment]
@JoMas971 Design updated
https://projects.invisionapp.com/d/main#/console/12026582/345528567/preview

**Comment by cfsnyder** [comment]
My two cents:

-  I like the double-arrow for switching between years because it seems more common and is therefore more intuitive. I'm not sure I would have discovered the year/month switcher that the clarity component uses, at least not right away.
- I think that the clarity component is actually a better design in terms of UX if we don't consider what users are familiar with. It's clearly easier to move between months/years with their approach, if you know that those options are there.

Ultimately it's Mathieu's decision, so I'll defer to him. If we use the clarity style, maybe we can find a way to make it more obvious that the month/year can be clicked?

**Comment by mathieupkf** [comment]
Design updated
https://projects.invisionapp.com/d/main#/console/12026582/345528567/preview

**Comment by JoMas971** [comment]
@mathieupkf Can you check that the date, time and datetime controls design are ok pls ?
