### ISSUE TITLE
[DATAGRID] columnSeparator on CsvExports not used

### ISSUE THREAD

**Issue by ariquinones** [ilanddev/ferui#106]
## When sending in a specific columnSeparator on a Datagrid's CsvExportParams the value is never used on the export

_Only type of export possible right now is a semi-colon ; separated values._

Looks like the column separator value is never taken into consideration when creating the export csv file. When the CsvCreator class createSerializingSession method gets called the params are never used and the default ones on the GridSerializer are used which is a ';'.
Found here I believe: `src/ferui-components/datagrid/services/exporter/grid-serializer.ts`

**Comment by ariquinones** [comment]
@JoMas971 I went ahead and PRed this issue for not using the column separator property for exports. But I also noticed that we don't seem to use other properties of the export params either (customHeader, customFooter, skipFooters). Is there a reason why?

**Comment by JoMas971** [comment]
@ariquinones Yeah i saw that, thank you by the way. About the other properties, i was planing to implement them but I didn't have the time to finish it totally. But i will take care of it at some point.
