### ISSUE TITLE
[WIDGET] Update paddings values

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#108]
The paddings in the header/footer of the widget should be 20px.
Also, the font size/weight of the Widget title is not right. We need to fix it as well. (refer to Mathieu's design)

@mathieupkf we will need the link to the new updated and validated design.

**Comment by mathieupkf** [comment]
This is what I have for the widget component. 
Let me know if we need more design specifications. 
https://invis.io/NBUHP4UVUXQ#/415989133_Widgets

**Comment by JoMas971** [comment]
@mathieupkf Thanks ! 
I have some questions for you though : 
- It is possible to not have a border between the header and content ?
- What about a possible footer section ? We need to have the design for it.

**Comment by mathieupkf** [comment]
@JoMas971 

- Yes, when we have only one element (one table) on the widget https://invis.io/FWMX6LFMJ7Y#/414303010_VM_Microsegmentation_01
- I don't see the point of providing a footer. Do you have specific cases in mind?

**Comment by JoMas971** [comment]
@mathieupkf It's just that those components are generic. We already have a footer for those components if we need it. So i'll just keep what we have.
