### ISSUE TITLE
[UI] Toast Notification Component

### ISSUE THREAD

**Issue by ariquinones** [ilanddev/ferui#117]
## Create a Toast Notification Component

_We need to create a generic Toast notification along with a notification service that will handle its control._

- FuiToastNotification and FuiToastNotificationService

**Comment by mathieupkf** [comment]
@ariquinones @JoMas971 - Here is the design for the Toast Component. 
https://invis.io/94XP1I12U7T

@JoMas971 - Do you remember the properties we've setup? (for the automatic close delay and the scale effect).

**Comment by JoMas971** [comment]
@mathieupkf Thanks for the design. And yeah i have the properties : 
- SlideIn duration = 800ms (the duration for the animation when the toast is display on screen)
- SlideOut duration = 400ms (the duration for the animation when the toast is removed)
- Auto SlideOut Delay = 10s (the duration of the toast on screen. The timer is stoped when user hover the toast with his mouse cursor and restart once he remove his mouse)

**Comment by mathieupkf** [comment]
Perfect, thanks @JoMas971 !

**Comment by ariquinones** [comment]
@mathieupkf thanks for the designs! 
Working on this now and some questions came up. So since we're adding this to FerUI should we not give the dev/user more granular control? Meaning I think we should have the defaults animation durations, but should we not allow the dev/user to change these if they want to? So they can adjust to their needs?
I've seen this example that looks pretty good while giving more options to configure based on needs. [Example](https://ej2.syncfusion.com/angular/demos/?_ga=2.34320545.1873696888.1591970064-215710079.1591970064#/material/toast/api)

@JoMas971 some questions for you too. We had talked about the action button being a TemplateRef, but again this is just an Angular concept. I'm thinking we should allow the user to send in an HTML element or string for us to treat as the html action button. And to add to that a callback method for when the user clicks on the action. An interface like this:

```
interface FuiToastNotificationActionInterface {
  template: string | HTMLElement;
  click?: () => void;
}
```
And lastly, what should we allow the dev/user to input for the icon? A template? Or keep it within the ferUI project and have them type in the clr icon name(string) for us to place in the toast notification for them?

**Comment by JoMas971** [comment]
@ariquinones By the way, we've moved to Jira + Bitbucket now. So please use Jira for ticket questions and bitbucket as repository.
