### ISSUE TITLE
[UI] Icons proportions looks wrong. 

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#12]
<img width="103" alt="capture d ecran 2019-01-25 a 16 47 32" src="https://user-images.githubusercontent.com/9723290/51756309-fc499080-20c0-11e9-8df9-55dd21d35905.png">

**Comment by mathieupkf** [comment]
@JoMas971 Can you check the size of the icons? 
Also can we remove the Cross icon ?

**Comment by JoMas971** [comment]
Well, about the size, they are different indeed but i don't know which size i should use for each of those icons...
And about the Cross icon, no, we can't remove it but we can improve its design. 
This icon allow a user to actually clear the select (it can be useful in some cases). It's part of  third-party library `ng-select` and developers can decide to hide or show this icon, but we need to handle the case when they actually want to display it ;-) .

**Comment by mathieupkf** [comment]
You'll find right sizes in a dedicated field here:
https://projects.invisionapp.com/d/main#/console/6412142/217015603/preview
And you'll be able to download a new icon for the clear option here:
https://projects.invisionapp.com/d/main#/console/12026582/330483189/preview

**Comment by mathieupkf** [comment]
@JoMas971 - When you'll implement the right Clear icon, don't forget to change the color hover style (change the red color for our dark blue).

**Comment by JoMas971** [comment]
@mathieupkf you can check the design there : https://68-155837827-gh.circle-artifacts.com/0/ferui/index.html
Let me know if it's all good for you.
Note the i've also included #17.

**Comment by mathieupkf** [comment]
@JoMas971 it looks like arrow & check icons are still too big (see screenshot)

**Comment by mathieupkf** [comment]
<img width="908" alt="Capture d’écran 2019-03-25 à 09 16 22" src="https://user-images.githubusercontent.com/9723290/54931514-c49f6f00-4ede-11e9-89b4-b7f9209826d5.png">

**Comment by JoMas971** [comment]
@mathieupkf i've updated the design. You can check it there : https://72-155837827-gh.circle-artifacts.com/0/ferui/index.html

**Comment by mathieupkf** [comment]
@JoMas971 Good for me
