### ISSUE TITLE
[UI] Remove calendar icon on date fields

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#15]
I think this icon don't works very well. Especially when we have also check and arrow icons.

**Comment by JoMas971** [comment]
@mathieupkf So you want me to delete this icon entirely ? That mean it will looks exactly the same than a regular input type text right ?

**Comment by mathieupkf** [comment]
@JoMas971 - Right. Is it possible to try on a field without the icon and i'll tell you if we keep it or not?

**Comment by JoMas971** [comment]
You can test it there : https://64-155837827-gh.circle-artifacts.com/0/ferui/index.html

**Comment by mathieupkf** [comment]
@JoMas971 I think it's great like this. Label that says "date" or something like that it's totally enough, we don't really need an icon.

**Comment by JoMas971** [comment]
@mathieupkf ok. will merge it to master then.
