### ISSUE TITLE
[UI] Issues for selected state on stroke lines (see screeshots)

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#16]
<img width="349" alt="Capture d’écran 2019-03-15 à 12 23 12" src="https://user-images.githubusercontent.com/9723290/54453691-74295400-471d-11e9-9268-2d931ff52dcb.png">
![Uploading Capture d’écran 2019-03-15 à 12.23.17.png…]()
![Uploading Capture d’écran 2019-03-15 à 12.23.21.png…]()

**Comment by JoMas971** [comment]
@mathieupkf - You can check the design there : https://71-155837827-gh.circle-artifacts.com/0/ferui/index.html

**Comment by mathieupkf** [comment]
@JoMas971 When you select an item on the dropdown menu and you close it, there is a bug on the selected field (right side of the field)

**Comment by mathieupkf** [comment]
<img width="284" alt="Capture d’écran 2019-03-25 à 09 19 38" src="https://user-images.githubusercontent.com/9723290/54931834-6cb53800-4edf-11e9-89e4-6e64465591f8.png">

**Comment by JoMas971** [comment]
@mathieupkf you can check it there : https://79-155837827-gh.circle-artifacts.com/0/ferui/index.html

**Comment by mathieupkf** [comment]
@JoMas971 perfect
