### ISSUE TITLE
[UI] Password fields - Font size is too small

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#18]
@JoMas971  - Not 100% sure for this one, can you check the font size you use to display the •••••• labels ? It looks very small.

**Comment by JoMas971** [comment]
@mathieupkf The input size is 14px with Roboto font and a font-weight of 700.

**Comment by mathieupkf** [comment]
@JoMas971 Ok so the font size is good. 
Maybe it's due to the type character you're using? Is it a "•" or a "." ?

**Comment by JoMas971** [comment]
@mathieupkf it's the default caracter for password inputs. So we can't change them. Just change the font-size and font-weight. So i could maybe raise those values a little bit.

This is how it looks with `font-size: 15px` and `font-weight: 900`.

![Screen Shot 2019-03-18 at 20 09 56](https://user-images.githubusercontent.com/3911470/54556838-0f3e5a00-49ba-11e9-8439-8b75622eb012.png)

**Comment by mathieupkf** [comment]
@JoMas971 - ok gotcha! Like that it's much better. We can use it.

**Comment by JoMas971** [comment]
@mathieupkf Alright then, will set it like that ;-)

**Comment by mathieupkf** [comment]
@JoMas971 - Perfect!
