### ISSUE TITLE
[UI] Radio button - Selected icon not centered and not rounded

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#21]
<img width="325" alt="Capture d’écran 2019-03-15 à 12 34 16" src="https://user-images.githubusercontent.com/9723290/54454301-c6b74000-471e-11e9-99f4-4ae3f76a8d03.png">

**Comment by JoMas971** [comment]
@mathieupkf Are you still see this issue on the latest build : 
https://63-155837827-gh.circle-artifacts.com/0/ferui/index.html

Because i don't see it even if i zoom by 300%.

**Comment by mathieupkf** [comment]
@JoMas971 Yep it's good now
