### ISSUE TITLE
[UI] We should have a visual response for disable state on checkboxes and radios

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#33]
## Describe the bug

_When you set the disabled state to true, we should have a visual response telling the user that he can't change their values_

**Comment by JoMas971** [comment]
@mathieupkf Can you check that everything is ok there please : https://81-155837827-gh.circle-artifacts.com/0/ferui/index.html

**Comment by mathieupkf** [comment]
@JoMas971 good for me
