### ISSUE TITLE
[DATAGRID] Datagrid design review

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#41]
@JoMas971 

Here is my feedbacks. Most of them are just minor issues. Very nice work man! 

- [x] Arrow sort icons too close to the label: use 7px margin
- [x] Number sort icons too close to the arrow: use 7px margin
- [x] Pager: all elements looks a little bit too big (arrows, selected square, margins between each numbers)
- [x] When you're scrolling faster, you see some white areas (because it's not loaded I suppose). Can we improve that?
- [x] Search field selected. On the right side of the field, there is a one pixel interval on the stroke. 
- [x] When you start typing, can we add our loader on the right side of the search field to display that we are loading. Right now it's hard to know that the search field is working. 
- [x] When it's loading, let's keep the elements on the header.

Filter feature:

- [x] Filter icon (with the dot) is not at the right size
- [x] Title label should be in bold. ("columns" label)
- [x] Font sizes on dropdown menus are not the same. Can we adjust that ? And use the one on the design as standard. 
- [x] When we select a lot of columns on the fist field, can we increase the field height instead of to make it scrollable?
- [x] Footer labels are not good. Should be bold. 
- [x] They are not well height centered too. 
- [x] Can we use this color #DF4242 as hovered on the font for the Clear all button (we don't need the hovered rectangle).
- [x] Let's add 30px margins at the left and right of the "Apply" label on the button.

Won 't do:

- [x] It looks like it's because some fields are too tiny to display well the dropdown. Maybe we should use the whole width when we have two fields. (225px width each).

**Comment by JoMas971** [comment]
Is part of #2

**Comment by JoMas971** [comment]
@mathieupkf it's ready for another review ! https://objective-booth-cd63b3.netlify.com/#/components/datagrid/client-side
Let me know if you still have some issues ;-).

**Comment by JoMas971** [comment]
@mathieupkf - Can you tell us if everything is good for you ? If it's the case, i'll let you add the "Design Validated" label and close the issue.

**Comment by JoMas971** [comment]
Everything look good. I'll close the issue then. Thanks @mathieupkf !

**Comment by mathieupkf** [comment]
Hey Jon, I’m adding design feedbacks and improvements for the datagrid here. 
InVision link : https://projects.invisionapp.com/d/main?origin=v7#/console/18730990/389837176/preview?scrollOffset=0

- Hovering style : there is one pixel space on the right side of the 3 dots icon background
- Hovering style : when the dropdown menu is open, we shouldn’t use this blue color for the background. This one was provided for the line selected state. 
- Hovering style : use « action » label button instead of the 3 dots icon. It wasn’t strong enough.
- Error messages designed

**Comment by mathieupkf** [comment]
@ariquinones - I've added here my datagrid comments. Let's discuss with @JoMas971 if they are part of FerUI. 

- When you’re hovering a line on the 3 dots icon area, we have sometime a displaying bug with the icon. Sometimes it is not displayed, do you see it? - Yeah i see it now, this looks to be a ferui datagrid bug so we may need to open an issue there

- When we have few lines displayed, the bottom line of the last line is missing - You're right this is a design issue with Ferui will address it with Jon

- The color of the « global search » label is not good. It’s weird because I’ve reviewed this component on FerUI and it’s good there. - Weirdest bug here, you're right and I can't seem to understand why this is happening, I will also address this with Jon 

- Right now we’re displaying « no results founds » when it’s loading. Can we display it only when there is really no results? - Will need to address Ferui side with Jon

**Comment by JoMas971** [comment]
@mathieupkf and @ariquinones : 
- For the first issue, yeah it is a datagrid issue indeed. I'll need to fix this out.
- About the line not showing, it is normal, that's because i have a rule that set the bottom line over each line and disable it for the last line. I'll do the same rule, but with top border and first row instead. That will fix this issue.
- About the color, if you don't see it on FerUI demo datagrid, that mean that there is another style that override my Datagrid style. This need to be addressed console side, not here.
- I'm working on the loading right now, it will be fixed on my next FerUI release. It will fix both issues that ari pointed out and listed in #77 .

I'll address all those issues (and the older ones too) once i have more time. For the moment, those issues doesn't break the datagrid, so they are not the highest priority.
