### ISSUE TITLE
[DATAGRID] Datagrid loading animation

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#42]
Hey @mathieupkf ,

i’ll need your help for infinite scrolling datagrid loading animation : check https://objective-booth-cd63b3.netlify.com/#/components/datagrid/infinite-server-side to see the ugly way i’m doing it now lol.
I know that other datagrid elements like filters, pager shouldn’t disappear anymore after first load (when in server side row model, i want to load the next or previous page). I’ll fix that later. 
But i would like to know, if the loader behaviour should be different than the global datagrid loader we have now (all rows hidden + loader in the middle) and how should it look then ?
ATM, it’s ugly... We need something better lol.
Maybe i can do something like : https://rintoj.github.io/ngx-virtual-scroller/samples (go to the the end of the page to see the infinite scrolling).
We can have a call to talk about it if you have some time.

**Comment by JoMas971** [comment]
Is part of #2

**Comment by mathieupkf** [comment]
hey @JoMas971. I don't see anything ugly here! Did you create this line loader in the meantime?

**Comment by JoMas971** [comment]
@mathieupkf indeed, i've updated the design after creating this ticket so it's not ugly anymore. 
But i would like to know if it's ok for you.
If the new design is ok for you i'll close this ticket, otherwise, if you have any requests, feel free to type them there.

**Comment by mathieupkf** [comment]
@JoMas971 - You can close it.

**Comment by JoMas971** [comment]
We decided to keep the design we talked about. So i'll close this issue.
