### ISSUE TITLE
[NG] Implement a dropdown menu

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#5]
For design : https://projects.invisionapp.com/d/main#/console/6412142/217015564/preview

- All options need to come from the user. It can be a `<button>` or `<a href="">`. We can also have a grouping of links with (or without) a title.
- The button itself can be a text an icon or an icon/text combo.
- It need to depend on the parent container but in some cases, we need to be able to change the parent container (i.e move the dropdown menu box to body like the `appendTo` option of [ng-select](https://ng-select.github.io/ng-select#/append-to-element)).
- The menu should be displayed on top or bottom of dropdown, depending on available space.
- The dropdown menu should remain open when the user scroll.
- (OPTIONAL) We need to be able to search for a value.

Actually, we want pretty much the same component than [clarity dropdown-menu](https://v2.clarity.design/dropdowns#examples).

**Comment by mathieupkf** [comment]
@JoMas971 - I've cleaned the design. You'll see that I simplified all cases. It's clearer now. I didn't really change the design, I just made some minor adjustments to have the right paddings, spacings... everywhere.
Let me know if you need anything else.
https://projects.invisionapp.com/d/main#/console/18730990/389837181/preview

**Comment by JoMas971** [comment]
@mathieupkf i've done the dropdown menu. You can check if everything is good at : https://5dc3151fc7c485c5cdea7d2f--john-ferui-demo.netlify.com/#/components/dropdown/home

**Comment by JoMas971** [comment]
@mathieupkf It's ready for another check https://5dc4392011a6a3e7807b265b--john-ferui-demo.netlify.com/
