### ISSUE TITLE
[TREE-VIEW] Tree View Component Design Review

### ISSUE THREAD

**Issue by ariquinones** [ilanddev/ferui#52]

**Comment by ariquinones** [comment]
Link of design: https://5dc058ae264ddf679c60fd4d--awesome-albattani-7ab95f.netlify.com/#/components/treeview

**Comment by JoMas971** [comment]
@mathieupkf Can you take a look at the tree-view component @ariquinones have published please ? At this step, we expect only a design checking (there is still some issues, specially with the server side version).
Thanks.

**Comment by mathieupkf** [comment]
Thanks @ariquinones - Here is my feedbacks:

- [ ] Let's use the white background version as default version. I don't see it rn. These 3 other variations are not important for now. I'd like to see all structures variations with the white version and the colored ones after. Like in my design. 
- [ ] We should increase the icon click area. It's pretty difficult to click on the icon
- [ ] Icon colors are not good. It should be gray.
- [ ] Hovering jcon style is missing
- [ ] When I open / close a section the associated label is moving. 
- [ ] Remove the drop shadow under selected states
- [ ] The width spacing between a parent and a child is 20px

**Comment by ariquinones** [comment]
@mathieupkf here's an updated link for the first round of updates: 
https://5dc24fa2a7ed948024a855a5--awesome-albattani-7ab95f.netlify.com/#/components/treeview

When you say we should increase the icon click area, what exactly do you mean? How far should a user be able to click to expand? 

Also could you somehow separate the parent vs child texts on your invision design? This way I can see the 20px spacing you're talking about

**Comment by mathieupkf** [comment]
@ariquinones Perfect! it looks good now.

**Comment by JoMas971** [comment]
@mathieupkf can you do another review please ? There is the new link : https://5dceccb028d0ea3e37896ab6--awesome-albattani-7ab95f.netlify.com/#/components/treeview
Thanks.

**Comment by mathieupkf** [comment]
@JoMas971 there are new elements to test since my last review?

**Comment by JoMas971** [comment]
@mathieupkf indeed. We added a new loader for infinite scrolling (check the server-side treeview).
Also, if you can test everything to see if we didn't break anything.

**Comment by JoMas971** [comment]
this issue has been fixed by #54. 
I'm closing the issue.
