### ISSUE TITLE
[Datagrid] items per page, error handling, infinite row model typeerror

### ISSUE THREAD

**Issue by ariquinones** [ilanddev/ferui#69]
## Multiple issues when working with datagrid

_Items per page dropdown gives options up to 100 items per page, but when user chooses anything above 20 items per page datagrid does not work._

_When using 5 as the beginning default to items per page, datagrid shows 5 items, but dropdown states 10._

_No error handling on Server/Infinite model. When the possibility of an error occurring the datagrid just stops working._

_On infinite row model, on first load we get a TypeError: Cannot read property 'clear' of undefined. Seems it doesn't read the IServerSideDatasource on first load._

**Comment by JoMas971** [comment]
Thank you for the list: 
- The 4th point is already fixed on my side, 
- The 1st and 2nd points are actually linked and i'm working on fixing those right now. 
- But nice catch on your 3rd point, indeed, i haven't though about handling the error... I'll ask @mathieu what i should do in case where we have an error.
