### ISSUE TITLE
[TREEVIEW] Tree view design fixes

### ISSUE THREAD

**Issue by ariquinones** [ilanddev/ferui#78]
## Need to address some Tree View design issues

* When you’re collapsing a folder, the loader icon is not at the right height, it should be at the exact same height than the loaded content. Loader icon should be align to the folder icon at the right.

* The scroll area does not fit the height background area

**Comment by ariquinones** [comment]
@mathieupkf you had said the scroll area doesn't fit the height of the background area in this image: 
![image](https://user-images.githubusercontent.com/16388180/78272603-f6242080-74ca-11ea-9127-8e6cf8c39265.png)

But so if we take out the padding of the height it would look like this: Is this what you want?
![Screen Shot 2020-04-02 at 10 18 57 AM](https://user-images.githubusercontent.com/16388180/78272973-6df24b00-74cb-11ea-8f41-7ad22970c203.png)

**Comment by mathieupkf** [comment]
@ariquinones - Yes this is what I want when we are scrolling but we need the top margin when we scroll to the top.

**Comment by ariquinones** [comment]
@mathieupkf ah okay gotcha!
Can you review this link with the updates: https://5e8666110256be85ebcfd993--awesome-albattani-7ab95f.netlify.com/#/components/treeview

The loader icon is the same height as the other tree nodes and the margin at the top only affects the first node while scrolling expands the whole height now

**Comment by mathieupkf** [comment]
Looks much cleaner! thanks @ariquinones -
I see only one detail : on the Non Root Tree View version there is a movement on the text when you're collapsing a list.

**Comment by ariquinones** [comment]
@mathieupkf yup i see it. Its fixed now here: https://5e873e4f4142b201935d6c2b--awesome-albattani-7ab95f.netlify.com/#/components/treeview

**Comment by ariquinones** [comment]
@mathieupkf can I get a validation on that text movement fix?  https://5e873e4f4142b201935d6c2b--awesome-albattani-7ab95f.netlify.com/#/components/treeview the branch will have the movement text fix

**Comment by mathieupkf** [comment]
@ariquinones - I see another issue ;(
When you unfold the tree, there is a transparent area at the bottom of the list which is useless. We can scroll much more than is necessary, do you see it?

**Comment by ariquinones** [comment]
Argh sorry about that @mathieupkf !! Fixing the padding introduced that issue. Okay this link should have all the fixes now. We switched up the demo page just a little bit to Jon's liking, but this link has everything from this issue fixed: https://5e8f5bc7d927e5fb906894bb--awesome-albattani-7ab95f.netlify.com/#/components/treeview/client-side

**Comment by mathieupkf** [comment]
Perfect! Thanks @ariquinones

**Comment by JoMas971** [comment]
I'll close this issue since it has been merged already.
