### ISSUE TITLE
[NG] Implement a widget component

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#8]
We need to add a widget component `<fui-widget>` which should depend on [Bootstrap card system](https://getbootstrap.com/docs/4.2/components/card/) for the design, but, we need to make it looks like [our design](https://projects.invisionapp.com/d/main#/console/6412142/225255583/preview)

- All titles shouldn't be a component attribute binding but they should be a sub-component (like `<fui-widget-title>` component) same apply actions (we will have `<fui-widget-actions>` component).
- If we want to add a description (or sub-title) under widget title, we should add it through a specific component `<fui-widget-description>`.
- The `<fui-widget-actions>` should be a wrapper that contains all possible actions (i.e link, buttons, submits, dropdowns, selects...) related to this widget.

And of course, all element that we include within the `<fui-widget>...</fui-widget>` component should be displayed as widget content.

**Comment by cfsnyder** [comment]
@JoMas971 - I think you have a pretty good list here. Really we just need to cover all of the existing cases that we already use in our console. A couple of additional things that come to mind that you should think about:
- an easy way to include a widget footer
- an easy way to include a grid, as we do on the top-level widget of most existing pages
- responsiveness considerations. e.g. the title and the actions must not overlap when the widget's width is not sufficient to display both at the same vertical position

**Comment by JoMas971** [comment]
That sounds good to me @cfsnyder. Your first and last point are ok, but what do you mean by 'Grid' ? 
Are you referring to this kind of grid ?

![Screen Shot 2019-03-15 at 17 30 50](https://user-images.githubusercontent.com/3911470/54446831-30980f80-4748-11e9-9c1f-5f802e69e91b.png)

If that's so, i rather like to not add this to the widget component itself but more has a global grid system (that we already have in ferui-design BTW). We have all bootstrap awesomeness in our arsenal, so i did rather like to use them as needed/wanted vs stick a specific grid class/system to the widget only and having another one in another place.

And lets be honest, it's pretty easy to do the grid manually using feruiDesign : 

```
<fui-widget>
    <fui-widget-title>My super title</fui-widget-title>
   <fui-widget-description>My description</fui-widget-description>
   <fui-widget-actions><button>Action1</button><button>Action1</button></fui-widget-actions>

   <!-- There, i put the grid that i make manually using feruiDesign's help -->
   <div class="container">
     <div class="row">
       <div class="col">
         1 of 3
       </div>
       <div class="col">
         2 of 3
       </div>
       <div class="col">
         3 of 3
       </div>
     </div>
   </div>

   <fui-widget-footer>My super footer</fui-widget-footer>
</fui-widget>
```

**Comment by cfsnyder** [comment]
@JoMas971  - I'm only suggesting that this use case is considered during development, not that it be explicitly supported as a feature of this component. For example, we would need an easy way to include a widget section that doesn't have any padding.

**Comment by JoMas971** [comment]
@cfsnyder actually, i think the default and only case with this widget component is to have 0 padding within the content section. It will be up to the injected content to have paddings through classes (`class="p-n"` which is bootstrap special class to set paddings or `class=custom` which is a special custom class you can create).
To me, the widget component should only act has a wrapper, and the only specific designed parts should be the header (title, subtitle and actions) and footer.
That way, we can easily use it and cover all cases ;-).
