### ISSUE TITLE
[TREEVIEW] Use an enum to list all possible Treeview events types

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#82]
For instance, when we want to handle NodeEvent, instead of using a number to track which event type we are getting it is better to use an enum like : `FuiTreeviewEvents.NODE_CLICKED` instead of knowing the number that correspond to this.

**Comment by ariquinones** [comment]
Didn't notice this was already done. I declare the enum just like all other FerUI enums 
`export enum TreeViewEventType {
  NODE_CLICKED,
  NODE_EXPANDED,
  NODE_COLLAPSED
}`
Was just using it wrong on the usage of the tree view component. 
Unless you want me to use the proper strings as their values?

**Comment by JoMas971** [comment]
Ok cool, that's a good news. But yeah, let convert it into string enums instead, it is more convenient for debugging to have string enums.
